default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: upl

test:
  <<: *default
  database: upl_test

production:
  <<: *default
  database: upl_production
